# frozen_string_literal: true

module Transponder
  module GraphQL
    module Types
      class AccessorialCategory < BaseEnum
        value 'AFTERHOURS_DELIVERY', value: :afterhours_delivery
        value 'AFTERHOURS_PICKUP', value: :afterhours_pickup
        value 'AIRPORT_DELIVERY', value: :airport_delivery
        value 'AIRPORT_PICKUP', value: :airport_pickup
        value 'AMUSEMENT_PARK_DELIVERY', value: :amusement_park_delivery
        value 'AMUSEMENT_PARK_PICKUP', value: :amusement_park_pickup
        value 'APPOINTMENT_DELIVERY', value: :appointment_delivery
        value 'APPOINTMENT_PICKUP', value: :appointment_pickup
        value 'ATHLETIC_FACILITY_DELIVERY', value: :athletic_facility_delivery
        value 'ATHLETIC_FACILITY_PICKUP', value: :athletic_facility_pickup
        value 'BREWERY_DELIVERY', value: :brewery_delivery
        value 'BREWERY_PICKUP', value: :brewery_pickup
        value 'CEMETERY_DELIVERY', value: :cemetery_delivery
        value 'CEMETERY_PICKUP', value: :cemetery_pickup
        value 'CHURCH_DELIVERY', value: :church_delivery
        value 'CHURCH_PICKUP', value: :church_pickup
        value 'CONSTRUCTION_DELIVERY', value: :construction_delivery
        value 'CONSTRUCTION_PICKUP', value: :construction_pickup
        value 'CONVENTION_DELIVERY', value: :convention_delivery
        value 'CONVENTION_PICKUP', value: :convention_pickup
        value 'CUSTOMS_BROKERAGE', value: :customs_brokerage
        value 'DOCK_DROPOFF', value: :dock_dropoff
        value 'DOCK_PICKUP', value: :dock_pickup
        value 'DRIVER_ASSIST', value: :driver_assist
        value 'EARLY_MORNING_DELIVERY', value: :early_morning_delivery
        value 'EARLY_MORNING_PICKUP', value: :early_morning_pickup
        value 'FAIR_DELIVERY', value: :fair_delivery
        value 'FAIR_PICKUP', value: :fair_pickup
        value 'FARM_DELIVERY', value: :farm_delivery
        value 'FARM_PICKUP', value: :farm_pickup
        value 'FITNESS_CENTER_DELIVERY', value: :fitness_center_delivery
        value 'FITNESS_CENTER_PICKUP', value: :fitness_center_pickup
        value 'FLATBED_DELIVERY', value: :flatbed_delivery
        value 'FLATBED_PICKUP', value: :flatbed_pickup
        value 'GOLF_COURSE_DELIVERY', value: :golf_course_delivery
        value 'GOLF_COURSE_PICKUP', value: :golf_course_pickup
        value 'GOVERNMENT_DELIVERY', value: :government_delivery
        value 'GOVERNMENT_PICKUP', value: :government_pickup
        value 'GROCERY_STORE_DELIVERY', value: :grocery_store_delivery
        value 'GROCERY_STORE_PICKUP', value: :grocery_store_pickup
        value 'GROCERY_WAREHOUSE_DELIVERY', value: :grocery_warehouse_delivery
        value 'GROCERY_WAREHOUSE_PICKUP', value: :grocery_warehouse_pickup
        value 'GUARANTEED_DELIVERY', value: :guaranteed_delivery
        value 'GUARANTEED_DELIVERY_AM', value: :guaranteed_delivery_am
        value 'GUARANTEED_DELIVERY_PM', value: :guaranteed_delivery_pm
        value 'HOSPITAL_DELIVERY', value: :hospital_delivery
        value 'HOSPITAL_PICKUP', value: :hospital_pickup
        value 'HOTEL_DELIVERY', value: :hotel_delivery
        value 'HOTEL_PICKUP', value: :hotel_pickup
        value 'INSIDE_DELIVERY', value: :inside_delivery
        value 'INSIDE_PICKUP', value: :inside_pickup
        value 'INSPECTION_SITE_DELIVERY', value: :inspection_site_delivery
        value 'INSPECTION_SITE_PICKUP', value: :inspection_site_pickup
        value 'JOBSITE_DELIVERY', value: :jobsite_delivery
        value 'JOBSITE_PICKUP', value: :jobsite_pickup
        value 'LIFTGATE_DELIVERY', value: :liftgate_delivery
        value 'LIFTGATE_PICKUP', value: :liftgate_pickup
        value 'MALL_DELIVERY', value: :mall_delivery
        value 'MALL_PICKUP', value: :mall_pickup
        value 'MARINA_DELIVERY', value: :marina_delivery
        value 'MARINA_PICKUP', value: :marina_pickup
        value 'MILITARY_SITE_DELIVERY', value: :military_site_delivery
        value 'MILITARY_SITE_PICKUP', value: :military_site_pickup
        value 'MINE_SITE_DELIVERY', value: :mine_site_delivery
        value 'MINE_SITE_PICKUP', value: :mine_site_pickup
        value 'MOTEL_DELIVERY', value: :motel_delivery
        value 'MOTEL_PICKUP', value: :motel_pickup
        value 'NURSING_HOME_DELIVERY', value: :nursing_home_delivery
        value 'NURSING_HOME_PICKUP', value: :nursing_home_pickup
        value 'PARK_DELIVERY', value: :park_delivery
        value 'PARK_PICKUP', value: :park_pickup
        value 'PRISON_DELIVERY', value: :prison_delivery
        value 'PRISON_PICKUP', value: :prison_pickup
        value 'RANCH_DELIVERY', value: :ranch_delivery
        value 'RANCH_PICKUP', value: :ranch_pickup
        value 'RESERVATION_DELIVERY', value: :reservation_delivery
        value 'RESERVATION_PICKUP', value: :reservation_pickup
        value 'RESIDENTIAL_DELIVERY', value: :residential_delivery
        value 'RESIDENTIAL_PICKUP', value: :residential_pickup
        value 'RESORT_DELIVERY', value: :resort_delivery
        value 'RESORT_PICKUP', value: :resort_pickup
        value 'RESTAURANT_DELIVERY', value: :restaurant_delivery
        value 'RESTAURANT_PICKUP', value: :restaurant_pickup
        value 'SCHOOL_DELIVERY', value: :school_delivery
        value 'SCHOOL_PICKUP', value: :school_pickup
        value 'STEEL_MILL_DELIVERY', value: :steel_mill_delivery
        value 'STEEL_MILL_PICKUP', value: :steel_mill_pickup
        value 'STORAGE_FACILITY_DELIVERY', value: :storage_facility_delivery
        value 'STORAGE_FACILITY_PICKUP', value: :storage_facility_pickup
        value 'UNIVERSITY_DELIVERY', value: :university_delivery
        value 'UNIVERSITY_PICKUP', value: :university_pickup
        value 'UTILITY_SITE_DELIVERY', value: :utility_site_delivery
        value 'UTILITY_SITE_PICKUP', value: :utility_site_pickup
        value 'WINERY_DELIVERY', value: :winery_delivery
        value 'WINERY_PICKUP', value: :winery_pickup
      end
    end
  end
end
