name: Deploy
on:
  push:
    branches:
      - main
env:
  BUNDLER_GITHUB_OAUTH_KEY: ${{ secrets.BUNDLER_GITHUB_OAUTH_KEY }}
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
jobs:
  checks:
    uses: ./.github/workflows/checks.yml
  deploy:
    name: Push
    needs: checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only --build-arg BUNDLER_GITHUB_OAUTH_KEY="$BUNDLER_GITHUB_OAUTH_KEY"
